




-- update leaders_icon
UPDATE SCHOOLS 
SET LEADERS_ICON = CASE
	WHEN LEADERS_SCORE > 0 AND LEADERS_SCORE <20 THEN 'VERY WEAK'
	WHEN LEADERS_SCORE < 40 THEN 'WEAK'
	WHEN LEADERS_SCORE < 60 THEN 'AVERAGE'
	WHEN LEADERS_SCORE < 80 THEN 'STRONG'
	WHEN LEADERS_SCORE < 100 THEN 'VERY STRONG'
    END
WHERE SCHOOL_ID = SCHOOL_ID;


DELIMITER //
CREATE PROCEDURE UPDATE_LEADERS_SCORE (IN IN_SCHOOL_IN INT, IN IN_LEADERS_SCORE INT)
BEGIN
	START TRANSACTION;
    UPDATE SCHOOLS 
    SET LEADERS_SCORE = IN_LEADERS_SCORE
    WHERE SCHOOL_ID = IN_SCHOOL_ID;
    IF IN_LEADERS_SCORE > 0 AND IN_LEADERS_SCORE <20 THEN UPDATE SCHOOLS SET LEADERS_ICON = 'VERY WEAK';
	ELSEIF IN_LEADERS_SCORE < 40 THEN UPDATE SCHOOLS SET LEADERS_ICON = 'WEAK'  WHERE SCHOOL_ID = IN_SCHOOL_ID;
	ELSEIF IN_LEADERS_SCORE < 60 THEN UPDATE SCHOOLS SET LEADERS_ICON = 'AVERAGE'  WHERE SCHOOL_ID = IN_SCHOOL_ID;
	ELSEIF IN_LEADERS_SCORE < 80 THEN UPDATE SCHOOLS SET LEADERS_ICON = 'STRONG'  WHERE SCHOOL_ID = IN_SCHOOL_ID;
	ELSEIF IN_LEADERS_SCORE < 100 THEN UPDATE SCHOOLS SET LEADERS_ICON = 'VERY STRONG'  WHERE SCHOOL_ID = IN_SCHOOL_ID;
	ELSEIF IN_LEADERS_SCORE >= 100 THEN ROLLBACK WORK;
    COMMIT;
    END IF;
END // 
DELIMITER ; 

